n1 = input()
size1 = int(input())
price1 = int(input())
n2 = input()
size2 = int(input())
price2 = int(input())

print(f"{n1},{n2}")
print(f"AverageSize={(size1+size2)//2}")
print(f"AveragePrice={(price1+price2)//2}")
